export const ADD_ATTACHMENT = 'ADD_ATTACHMENT';
export const DELETE_ATTACHMENT = 'DELETE_ATTACHMENT';
export const ATTACHMENT_ERROR = 'ATTACHMENT_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const UPDATE_STATUS = 'UPDATE_STATE';